name: CI (main)

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rspec:
    permissions:
      contents: read
    uses: ./.github/workflows/rspec.yml

  docker:
    needs: rspec
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/docker.yml
    secrets: inherit
