name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rspec:
    permissions:
      contents: read
    uses: ./.github/workflows/rspec.yml

  docker:
    needs: rspec
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  example-action:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: iguchi1124/example-action@main
        with:
          message: 'Hello world'
