name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  rspec:
    uses: ./.github/workflows/rspec.yml

  docker:
    uses: ./.github/workflows/docker.yml
