name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  rspec:
    timeout-minutes: 30
    permissions:
      contents: read
    uses: ./.github/workflows/rspec.yml
