name: rspec

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: push
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: example_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root@127.0.0.1:3306/example_test
        run: |
          bundle exec rails db:migrate
          bundle exec rspec

  docker:
    runs-on: ubuntu-latest
    needs: rspec
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: iguchi1124/rails-gh-actions-example:latest
