name: Pull Request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  rspec:
    timeout-minutes: 30
    permissions:
      contents: read
    uses: ./.github/workflows/rspec.yml

  private-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: iguchi1124/private-action@main
        with:
          who-to-greet: 'Mona the Octocat'
