name: Pull Request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  rspec:
    permissions:
      contents: read
    uses: ./.github/workflows/rspec.yml

  example-action:
    needs: rspec
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: iguchi1124/example-action@main
        with:
          message: 'Hello world'
